# -*- coding: utf-8 -*-
r"""Generate static/theme.css from shelfready_ui.theme.

The desktop app and the site must not drift into two different greens, so
the palettes stay single-sourced in theme.py and this script projects them
into CSS custom properties. Regenerate after editing THEMES:

    .venv\Scripts\python.exe -m shelfready_web.build_theme_css

tests/test_web.py fails if the checked-in file is stale, so a forgotten
regeneration is caught in CI rather than in production.
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from shelfready_ui import theme

OUT_PATH = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "static", "theme.css")

HEADER = """/* GENERATED by shelfready_web/build_theme_css.py - do not edit.
   Source of truth: shelfready_ui/theme.py (THEMES).
   Regenerate:  python -m shelfready_web.build_theme_css  */
"""


def _vars(palette, indent="  "):
    return "\n".join(f"{indent}--{key.lower().replace('_', '-')}: {value};"
                     for key, value in palette.items())


def render():
    """The full stylesheet text."""
    default = theme.THEMES[theme.DEFAULT_THEME]
    parts = [HEADER, "", f":root {{\n{_vars(default)}\n}}", ""]

    for name, palette in theme.THEMES.items():
        # Explicit choice wins in both directions, so the toggle can always
        # override what the OS reports.
        parts.append(f':root[data-theme="{name}"] {{\n{_vars(palette)}\n}}')
        parts.append("")

    # "warm" is the light-surfaced palette and the default is the dark one,
    # so those are what a viewer asking for light or dark should get. The
    # aliases matter wherever something other than our own toggle stamps the
    # root — an embedding host, or a browser extension — which stamps the
    # generic "light"/"dark" rather than our palette names.
    light = theme.THEMES["warm"]
    parts.append(f':root[data-theme="light"] {{\n{_vars(light)}\n}}')
    parts.append("")
    parts.append(f':root[data-theme="dark"] {{\n{_vars(default)}\n}}')
    parts.append("")

    parts.append("@media (prefers-color-scheme: light) {")
    parts.append(f'  :root:not([data-theme]) {{\n{_vars(light, "    ")}\n  }}')
    parts.append("}")
    parts.append("")
    return "\n".join(parts)


def main():
    text = render()
    with open(OUT_PATH, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)
    print(f"wrote {OUT_PATH} ({len(text)} bytes)")


if __name__ == "__main__":
    main()
